<?php
// auto-generated by sfPropelCrud
// date: 2009/03/15 20:44:07
?>
<?php use_helper('Object') ?>

<h1><? echo ($sf_context->getActionName() == 'create')? "Create":"Edit" ?> Bank</h1>

<?php echo form_tag('bank/update') ?>

<?php echo object_input_hidden_tag($bank, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($bank, 'getName', array (
  'size' => 10,
)) ?></td>
</tr>
<tr>
  <th>Instruments:</th>
  <td>
  <?php echo object_select_tag('instruments','getInstruments', array (
  'related_class' => 'Instrument',
  'multiple' => 'multiple',
)) ?>
  </td>
</tr>
<tr>
  <th>Share:</th>
  <td><?php echo object_checkbox_tag($bank, 'getShare') ?> <a href="javascript:;" name="share" onclick="whatsShare()">What's this?</a></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($bank->getId()): ?>
  &nbsp;<?php echo link_to('delete', 'bank/delete?id='.$bank->getId(), 'post=true&confirm=Are you sure?') ?>
  &nbsp;<?php echo link_to('cancel', 'bank/show?id='.$bank->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'bank') ?>
<?php endif; ?>
</form>
