<?php
// auto-generated by sfPropelCrud
// date: 2009/03/15 20:44:07

  if ($sf_user->getSubscriber() == $bank->getOwner()) {
	echo link_to('[Edit Bank]', 'bank/edit?id='.$bank->getId());
  }
?>
<h1><?=$bank->getName()?></h1>
<h5>Owner: <?php echo $bank->getOwner() ?></h5>
<br />

<hr />
<? use_helper('Form'); ?>

<?php echo form_tag('instrument/export') ?>
<?php echo input_hidden_tag('bank',$bank->getId()); ?>
<?php echo submit_tag('  Export to SAV  '); ?>
<hr />
<br />

<h2>Instruments in <?=$bank->getName()?></h2>
<div class="home_instrument">
<ul>
  <li><strong>Name</strong></li>
  <li><strong>Type</strong></li>
  <li><strong>Author</strong></li>
</ul>
</div>
<? foreach ($instruments as $instrument): ?>
  <? echo include_partial('instrument/instrument_list', array('instrument' => $instrument)) ?>
<? endforeach; ?>

<hr />
