default:
  http_metas:
    content-type: text/html

  metas:
    title:        Chip Patch Book
    robots:       index, follow
    description:  Chip music patch cookbook website. Find instrument patches for various 8-bit related software.
    keywords:     lsdj, 8-bit, chipmusic, chiptune
    language:     en

  stylesheets:    [main]

  javascripts:    [main, turbov110]

  has_layout:     on
  layout:         layout
