<?php
// auto-generated by sfPropelCrud
// date: 2009/01/25 05:42:40
?>
<?
  $USER = $sf_user->getSubscriber();
  if ($USER == $instrument->getOwner() || $USER == $instrument->getAuthor()) {
	echo link_to('[Edit Instrument]', 'instrument/edit?id='.$instrument->getId());
  }
?>
<div id="sidebar">
  <div id="tagCloud">
    <h2>tags</h2>
 
    <ul id="tags">
      <?php include_partial('tag/tags', array('instrument' => $instrument, 'tags' => $instrument->getTags())) ?> 
    </ul>
  </div>

<?php if ($sf_user->isAuthenticated()): ?>
  <div id="tagIt">Tag it:
    <?php echo form_tag('@tag_add') ?>
      <?php echo input_hidden_tag('instrument_id', $instrument->getId()) ?>
      <?php echo input_hidden_tag('referer', 'http://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']) ?>
      <?php echo input_tag('tag', '') ?>
      <?php echo submit_tag('Tag') ?> (separate tags by spaces)
    </form>
  </div>
<?php endif; ?>

<h2 id="iLikeh2">Popularity: <?=$instrument->getPopularity()?></h2>
<?php if ($sf_user->isAuthenticated()): ?>
  <div id="iLike">
	<?php echo form_tag('@iLike') ?>
      <?php echo input_hidden_tag('instrument_id', $instrument->getId()) ?>
	  <? echo submit_tag('i like this'); ?>
	</form>
  </div>
<?php endif; ?>

<?php use_helper('Validation') ?>
<h2>Sample</h2>
<?php if ($instrument->getSample()): ?>
  <?php myTools::playSample($instrument->getSample()) ?>
<?php else: ?>
<div>We don't have one yet.

  <?php if ($sf_user->isAuthenticated()): ?>
	Why don't you upload one?<br/>
	<?php echo form_tag('instrument/upload', 'multipart=true') ?>
	  <?php echo input_hidden_tag('instrument_id', $instrument->getId()) ?>
      <span><?php echo form_error('file') ?></span><br />
	  <?php echo input_file_tag('file',array('size'=>'12')) ?><br />
	  <?php echo submit_tag('Upload') ?> <span style="color: red">(MP3 64kb limit)</span>
	</form>
  <?php endif; ?>
</div>
<?php endif; ?>

</div>

<h1><?php echo $instrument->getName() ?></h1>
<h5><?php echo $instrument->getUpdatedAt() ?></h5>
<h5>Submitted by: <?php echo link_to($instrument->getOwner(),'@user?username='.$instrument->getOwner()) ?></h5>
<h5>Original Author: <?php echo link_to($instrument->getAuthor(),'@author?author='.$instrument->getAuthorStrip()) ?></h5>

<?php include_partial(sfConfig::get('app_tag'),array('instrument'=>$instrument)); ?>

<div class="metainfo">
  <h2>Description</h2>
	<q><?php echo $instrument->getDescription() ?></q>
	<hr />

<?php include_partial('comments', array('instrument' => $instrument, 'comments' => $instrument->getComments())) ?> 

	<?php if ($sf_user->isAuthenticated()): ?>
	<a name="postComment"></a>
	<div id="postComment"><strong>Post Comment</strong>
	    <?php echo form_tag('@comment_add') ?>
	      <?php echo input_hidden_tag('instrument_id', $instrument->getId()) ?>
	      <?php echo input_hidden_tag('referer', 'http://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']) ?>
		  <textarea name="comment" id="comment"></textarea>
	      <?php echo submit_tag('Submit') ?>
		</form>
	</div>
	<?php else : ?>
	  <?php echo link_to('post a comment','@login',array('class'=>'postComment')) ?>
	<?php endif; ?>

</div>
